export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/home'
export const INSTRUCTOR_ROUTE = '/instructors'
export const ENROLLMENT_ROUTE = 'enrollments'